### PR TITLE
Adding Configuring Issue Template section to README

### PR DESCRIPTION
**Pull request by smrghsh**
i have an idea for what were going to do

### CODE REVIEW

**Comment by rouxpz** [comment]
GitHub documentation for issue templates: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by prodka** [comment]
hi samir, I'm slightly confused haha but I am here to say hi

**Comment by KatieLuo** [comment]
me too!

**Comment by deannagelosi** [comment]
the bug issue template for p5.js is located here: https://github.com/processing/p5.js/blob/main/.github/ISSUE_TEMPLATE/5-found-a-bug.yml

**Pull request merged**
